### ISSUE TITLE
Expand listing to Amazon Skill Store Germany

### ISSUE THREAD

**Issue by dschroed** [cakebarIO/QuickAdd-for-Todoist#3] opened 2024-06-27 20:55 UTC
**Is your feature request related to a problem? Please describe.**
Currently the skill can only be purchased in the US on Amazon.com. Preventing several other users across the globe. 

**Describe the solution you'd like**
Please, enable your skill for all / other Amazon.xx skill stores, like the German market. 

**Describe alternatives you've considered**
Currently not seeing any alternative, neither Todoist adding a native solution. :-/

**Comment by cakebarIO** [comment] 2024-07-05 19:08
Thank you for your suggestion.

I am currently working on getting the skill certified in other locales. This has proven to be more-difficult than it should be!

To start, I am trying to add this to most English-speaking countries. As for non-English-locales, I need to figure out a way to accurately translate for each.

**Comment by cakebarIO** [comment] 2024-07-06 14:59
Closing as duplicate of https://github.com/cakebarIO/QuickAdd-for-Todoist/issues/2

**Closed as completed** 2024-07-06 14:58 UTC
Labels: duplicate
